name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast1
  SERVICE_NAME: ${{ secrets.GCP_CLOUD_RUN_PRODUCTION_INSTANCE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Check and Create Docker Repository
        run: |
          REPO_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo"
          if ! gcloud artifacts repositories list --location=${{ env.REGION }} | grep -q "docker-repo"; then
            echo "Creating Docker repository..."
            gcloud artifacts repositories create docker-repo \
              --repository-format=docker \
              --location=${{ env.REGION }} \
              --description="Docker repository for production deployment"
          else
            echo "Docker repository already exists, skipping creation"
          fi

      - name: Build and Push Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/production-app:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/production-app:${{ github.sha }}

      - name: Check if Cloud Run service exists
        id: check-service
        run: |
          if gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and Deploy New Service
        if: steps.check-service.outputs.exists == 'false'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/production-app:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated

      - name: Update Existing Service
        if: steps.check-service.outputs.exists == 'true'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/production-app:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed
